### ISSUE TITLE
Does not work in Chrome

### ISSUE THREAD

**Issue by Andr3as** [Andr3as/Codiad-Minimap#1]
Chrome does not display the minimap.

**Comment by pwFoo** [comment]
Tested latest docker image / container codiad with minimap. Minimap is visible in chrome, but to small.

**Comment by Andr3as** [comment]
Okay, it's mac specific 🙈. Thanks for your comment.
Chrome on Mac
![chromeonmac](https://cloud.githubusercontent.com/assets/4389878/22174903/2ae490bc-dfea-11e6-95a2-9710e3c71b5a.png)
Chrome on Ubuntu
![chromeonubuntu](https://cloud.githubusercontent.com/assets/4389878/22174908/399043ae-dfea-11e6-90e4-9124ef422d63.png)
Chrome on Windows
![chromeonwindows](https://cloud.githubusercontent.com/assets/4389878/22174910/4338dc0e-dfea-11e6-8b8e-1d54366c09bf.png)

**Comment by Andr3as** [comment]
Should now also work in Chrome on Mac: dfde27f
